---
title: "Presentación: Fundamentos de Git y GitHub"
author: "Joan Vicenç Cladera Salvà"
format: html
editor: visual
---

## Repositorio

El repositorio donde está el código de esta tarea para la obtención del certificado de aprovechamiento del curso "Fundamentos de Git y GitHub y su aplicación en proyectos colaborativos y reproducibles en R y RStudio" es:

"[github.com](https://github.com/JoanVii/Treball_Aliments)"

### Readme

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

### Issue

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

### Participantes

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Historial de commits

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Documentos de Quarto

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

### Word

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code

## Organización y problemas

When you click the **Render** button a document will be generated that includes:

-   Content authored with markdown
-   Output from executable code
